default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "Starting..."

stages:
  - build_docker
  - build_typescript
  - build_assets


build_typescript_job:
  image: node:22-alpine
  stage: build_typescript
  script:
    - echo "Installing dependencies..."
    - npm ci
    - npm i @types/express
    - echo "Building TypeScript..."
    - npm run build

build_assets_job:
  image: node:22-alpine
  stage: build_assets
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Building assets..."
    - npm run build:css
