stages:
  - lint
  - build_assets
  - deploy

type_check:
  image: node:22-alpine
  stage: lint
  script:
    - npm ci
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/

build_css:
  image: node:22-alpine
  stage: build_assets
  needs:
    - type_check
  script:
    - npm ci
    - npm run build:css
    - '[ -f dist/public/styles/styles.css ] && echo "CSS built OK" || (echo "CSS build failed" && exit 1)'
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
      
railway_deploy:
  image: ghcr.io/railwayapp/cli:latest
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
      when: always
    - when: never
  variables:
    SVC_ID: "$RAILWAY_SERVICE_ID"

  script:
    # Wrap commands in single quotes to avoid YAML misparsing of colons, quotes, etc.
    - 'echo "Deploying to Railway service ID: $SVC_ID"'
    - 'railway up --service="$SVC_ID" --yes'
