default:
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  before_script:
    - echo "Starting..."

variables:
  # Ensure devDependencies are installed for build
  NODE_ENV: development

stages:
  - build_docker
  - build_typescript
  - build_assets
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build_docker_job:
  stage: build_docker
  script:
    - echo "Building docker..."
    - docker build -t leaguele-app .
    - docker save leaguele-app > image.tar
  artifacts:
    paths:
      - image.tar
    expire_in: 10 minutes

build_typescript_job:
  image: node:22-alpine
  stage: build_typescript
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Building TypeScript..."
    - npm run build

build_assets_job:
  image: node:22-alpine
  stage: build_assets
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Building assets..."
    - npm run build:css

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

railway-deploy:
  stage: deploy
  image: ghcr.io/railwayapp/cli:latest
  variables:
    SVC_ID: 05835fa3-578b-45f7-a513-ba13aaea8d60
  script:
    - railway up --service=$SVC_ID
