stages:
  - build_docker
  - build_typescript
  - build_assets

build_docker_job:
    stage: build_docker
    script: 
      echo "Building docker..."
      docker build -t leaguele-app .
      docker save leaguele-app > image.tar
    artifacts:
      paths:
        - image.tar
      expire_in: 12 minutes

build_typescript_job:
  image: node:22-alpine
  stage: build_typescript
  script:
    echo "Building TypeScript..."
    npm run build

build_assets_job:
  image: node:22-alpine
  stage: build_assets
  script:
    echo "Building assets..."
    npm run build:css
