variables:
  # Ensure devDependencies are installed for build
  NODE_ENV: development

stages:
  - build_typescript
  - build_assets

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

build_typescript_job:
  image: node:22-alpine
  stage: build_typescript
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Building TypeScript..."
    - npm run build

build_assets_job:
  image: node:22-alpine
  stage: build_assets
  script:
    - echo "Installing dependencies..."
    - npm ci
    - echo "Building assets..."
    - npm run build:css
